=== upadhyay-rajesh/xmltraining/xml_training/xsl/JAVA-XML/calls.dtd
<!ELEMENT PHONE_RECORDS (CALL)*>
<!ELEMENT CALL (FROM, DATE, TIME, DESTINATION, DURATION, CALL_PROMOTION? )>
<!ELEMENT FROM (#PCDATA)>
<!ELEMENT DATE (#PCDATA)>
<!ELEMENT TIME EMPTY>
<!ATTLIST TIME HOUR NMTOKEN #REQUIRED MINUT NMTOKEN #REQUIRED>
<!ELEMENT DESTINATION (#PCDATA)>
<!ATTLIST DESTINATION CITY NMTOKEN #REQUIRED COUNTRY NMTOKEN #REQUIRED STATE NMTOKEN #IMPLIED>
<!ELEMENT DURATION (#PCDATA)>
<!ATTLIST DURATION HOUR NMTOKEN #REQUIRED MINUT NMTOKEN #REQUIRED>
<!ELEMENT CALL_PROMOTION (#PCDATA)>

=== upadhyay-rajesh/xmltraining/xml_training/xsl/JAVA-XML/calls.xml
<?xml version="1.0" ?>
<?xml-stylesheet type="text/xsl" href="calls.xsl" ?>
<!DOCTYPE movies SYSTEM "calls.dtd">
<PHONE_RECORDS>
  <CALL>
    <FROM>703-433-5678</FROM>
    <DATE>5/5/2000</DATE>
    <TIME HOUR="19" MINUTE="32" />
    <DESTINATION STATE="BANGALORE" CITY="KAMAK" COUNTRY="INDIA">510-798-8390</DESTINATION>
    <DURATION HOUR="1" MINUTE="3"></DURATION>
    <CALL_PROMOTION>HALF PRICE</CALL_PROMOTION>
    
  </CALL>
<CALL>
    <FROM>703-433-5679</FROM>
    <DATE>6/5/2000</DATE>
    <TIME HOUR="20" MINUTE="32" />
    <DESTINATION STATE="BANG" CITY="KAMA" COUNTRY="INDI">510-798-839</DESTINATION>
    <DURATION HOUR="11" MINUTE="13"></DURATION>
    <CALL_PROMOTION>HALF PRICE</CALL_PROMOTION>
    
  </CALL>
<CALL>
    <FROM>703-5679</FROM>
    <DATE>6/5/200</DATE>
    <TIME HOUR="2" MINUTE="32" />
    <DESTINATION STATE="BAN" CITY="KAMA" COUNTRY="INDI">510-798-839</DESTINATION>
    <DURATION HOUR="11" MINTE="13"></DURATION>
    <CALL_PROMOTION>HALF PICE</CALL_PROMOTION>
    
  </CALL>
</PHONE_RECORDS>
