<?xml version="1.0" standalone="yes"?>
<!DOCTYPE catalog[
<!ELEMENT CATALOG (PRODUCT+)>
<!ELEMENT PRODUCT (SPECIFICATIONS+,PRICE+,NOTES?)>
<!ATTLIST PRODUCT NAME CDATA #REQUIRED>

<!ELEMENT SPECIFICATIONS (#PCDATA)>
<!ATTLIST SPECIFICATIONS SIZE CDATA #REQUIRED 
						 COLOR CDATA #REQUIRED>
<!ELEMENT PRICE (#PCDATA)>
<!ATTLIST PRICE WHOLESALE NMTOKEN #REQUIRED
				RETAIL NMTOKEN #REQUIRED
				SALES.TAX NMTOKEN #IMPLIED>
<!ELEMENT NOTES (#PCDATA)>
]>
<CATALOG>
	<PRODUCT NAME="T.SHIRT">
		<SPECIFICATIONS SIZE="XL" COLOR="RED"/>
		<PRICE WHOLESALE="9.99" RETAILS="79.95" SALES.TAX="4.45"/>
		<NOTES>DILBERT </NOTES>
	</PRODUCT>
	<PRODUCT NAME="PANT">
		<SPECIFICATIONS SIZE="XL" COLOR="GREEN"/>
		<PRICE WHOLESALE="9.99" RETAILS="79.95" SALES.TAX="4.45"/>
		<NOTES>DILBERT</NOTES>
	</PRODUCT>
</CATALOG>
	
