=== upadhyay-rajesh/xmltraining/xml_training/dtd/Movie.dtd
<!ELEMENT movies (movie)+>
<!ELEMENT movie (title, writer+, producer+, director+, actor*, comments?)>
<!ATTLIST movie
  type (drama | comedy | adventure | sci-fi | mystery | horror | romance | documentary) "drama"
  rating (G | PG | PG-13 | R | X) "PG"
  review (1 | 2 | 3 | 4 | 5) "3"
  year CDATA #IMPLIED>
<!ELEMENT title (#PCDATA)>
<!ELEMENT writer (#PCDATA)>
<!ELEMENT producer (#PCDATA)>
<!ELEMENT director (#PCDATA)>
<!ELEMENT actor (#PCDATA)>
<!ELEMENT comments (#PCDATA)>

=== upadhyay-rajesh/xmltraining/xml_training/dtd/movie.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE movies SYSTEM "Movie.dtd">
<movies>
  <movie type="vxv" rating="PG-13" review="5" year="1987">
    <title>Raising Arizona</title>
    <writer>Ethan Coen</writer>
    <producer>Ethan Coen</producer>
    <director>Joel Coen</director>
    <actor>Nicolas Cage</actor>
    <actor>Holly Hunter</actor>
    <comments>Classic</comments>
  </movie>
</movies>
